# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
apiVersion: v2
name: lfx-v2-committee-service
description: LFX Platform V2 Committee Service chart
type: application
version: 0.2.7
appVersion: "latest"
