# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
{{- if .Values.nats.committees_kv_bucket.creation }}
apiVersion: jetstream.nats.io/v1beta2
kind: KeyValue
metadata:
  name: {{ .Values.nats.committees_kv_bucket.name }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.nats.committees_kv_bucket.keep }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
spec:
  bucket: {{ .Values.nats.committees_kv_bucket.name }}
  history: {{ .Values.nats.committees_kv_bucket.history }}
  storage: {{ .Values.nats.committees_kv_bucket.storage }}
  maxValueSize: {{ .Values.nats.committees_kv_bucket.maxValueSize }}
  maxBytes: {{ .Values.nats.committees_kv_bucket.maxBytes }}
  compression: {{ .Values.nats.committees_kv_bucket.compression }}
{{- end }}
---
{{- if .Values.nats.committees_settings_kv_bucket.creation }}
apiVersion: jetstream.nats.io/v1beta2
kind: KeyValue
metadata:
  name: {{ .Values.nats.committees_settings_kv_bucket.name }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.nats.committees_settings_kv_bucket.keep }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
spec:
  bucket: {{ .Values.nats.committees_settings_kv_bucket.name }}
  history: {{ .Values.nats.committees_settings_kv_bucket.history }}
  storage: {{ .Values.nats.committees_settings_kv_bucket.storage }}
  maxValueSize: {{ .Values.nats.committees_settings_kv_bucket.maxValueSize }}
  maxBytes: {{ .Values.nats.committees_settings_kv_bucket.maxBytes }}
  compression: {{ .Values.nats.committees_settings_kv_bucket.compression }}
{{- end }}
