# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
apiVersion: heimdall.dadrus.github.com/v1alpha4
kind: RuleSet
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - id: "rule:lfx:lfx-v2-committee-service:openapi:get"
      match:
        methods:
          - GET
          - HEAD
        routes:
          - path: /_committees/openapi.json
          - path: /_committees/openapi.yaml
          - path: /_committees/openapi3.json
          - path: /_committees/openapi3.yaml
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        - authorizer: allow_all
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}
    - id: "rule:lfx:lfx-v2-committee-service:committees:create"
      match:
        methods:
          - POST
        routes:
          - path: /committees
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: json_content_type
        - authorizer: openfga_check
          config:
            values:
              relation: writer
              object: "project:{{ "{{- .Request.Body.project_uid -}}" }}"
        {{- else -}}
        # When OpenFGA is disabled, allow all requests
        # (Only meant for *local development* because OpenFGA should be enabled when deployed)
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-committee-service:committees:get"
      match:
        methods:
          - GET
        routes:
          - path: /committees/:uid
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: viewer
              object: "committee:{{ "{{- .Request.URL.Captures.uid -}}" }}"
        {{- else -}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-committee-service:committee_settings:get"
      match:
        methods:
          - GET
        routes:
          - path: /committees/:uid/settings
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: auditor
              object: "committee:{{ "{{- .Request.URL.Captures.uid -}}" }}"
        {{- else -}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-committee-service:committees:update"
      match:
        methods:
          - PUT
        routes:
          - path: /committees/:uid
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: writer
              object: "committee:{{ "{{- .Request.URL.Captures.uid -}}" }}"
        {{- else -}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-committee-service:committee_settings:update"
      match:
        methods:
          - PUT
        routes:
          - path: /committees/:uid/settings
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: writer
              object: "committee:{{ "{{- .Request.URL.Captures.uid -}}" }}"
        {{- else -}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-committee-service:committees:delete"
      match:
        methods:
          - DELETE
        routes:
          - path: /committees/:uid
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: writer
              object: "committee:{{ "{{- .Request.URL.Captures.uid -}}" }}"
        {{- else -}}
        # When OpenFGA is disabled, allow all requests
        # (Only meant for *local development* because OpenFGA should be enabled when deployed)
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-committee-service:committee_members:create"
      match:
        methods:
          - POST
        routes:
          - path: /committees/:uid/members
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: writer
              object: "committee:{{ "{{- .Request.URL.Captures.uid -}}" }}"
        {{- else -}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-committee-service:committee_members:get"
      match:
        methods:
          - GET
        routes:
          - path: /committees/:uid/members/:member_uid
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: viewer
              object: "committee:{{ "{{- .Request.URL.Captures.uid -}}" }}"
        {{- else -}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-committee-service:committee_members:update"
      match:
        methods:
          - PUT
        routes:
          - path: /committees/:uid/members/:member_uid
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: writer
              object: "committee:{{ "{{- .Request.URL.Captures.uid -}}" }}"
        {{- else -}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-committee-service:committee_members:delete"
      match:
        methods:
          - DELETE
        routes:
          - path: /committees/:uid/members/:member_uid
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: writer
              object: "committee:{{ "{{- .Request.URL.Captures.uid -}}" }}"
        {{- else -}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}
